title: "홍길동"
description: "Unreal Engine Client Programmer | EVR Studio | ProjectTH"
url: "https://yourusername.github.io"
theme: sproogen/resume-theme

# Profile information
name: "홍길동"
email: "hong@example.com"
github_username: "yourusername"
linkedin_username: "yourlinkedin"
twitter_username: "yourtwitter"
avatar: "/assets/img/profile.jpg"

# Your experience
experience:
  - company: "EVR Studio"
    position: "Client Programmer"
    duration: "Jan 2023 - Present"
    summary: "ProjectTH 개발에 참여..."

# Projects
projects:
  - name: "ProjectTH"
    link: "https://evrstudio.com/projectth"
    description: "차세대 UE 기반의 포스트 아포칼립스 게임"

# Blog
blog:
  - title: "Unreal Engine에서 Dynamic Foliage 처리"
    link: "https://yourusername.github.io/blog/ue-foliage"
  - title: "FFmpeg을 이용한 프레임 비교 도구 만들기"
    link: "https://yourusername.github.io/blog/ffmpeg-diff-tool"
