theme: null
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
paginate: 5
paginate_path: "/page:num/"
title: My Blog
description: A blog inspired by jojoldu.github.io
